import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1785447378914 implements MigrationInterface {
    name = 'InitialSchema1785447378914'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // uuid_generate_v4() below comes from this extension.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "regions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name_uz" character varying(120) NOT NULL, "name_ru" character varying(120) NOT NULL, "slug" character varying(80) NOT NULL, "lat" double precision, "lng" double precision, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_regions_slug" ON "regions" ("slug") `);
        await queryRunner.query(`CREATE TABLE "districts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name_uz" character varying(120) NOT NULL, "name_ru" character varying(120) NOT NULL, "slug" character varying(80) NOT NULL, "region_id" uuid NOT NULL, CONSTRAINT "PK_972a72ff4e3bea5c7f43a2b98af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_districts_region_slug" ON "districts" ("region_id", "slug") `);
        await queryRunner.query(`CREATE INDEX "idx_districts_region" ON "districts" ("region_id") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'moderator', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_language_enum" AS ENUM('uz', 'ru')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "phone" character varying(20) NOT NULL, "name" character varying(120), "avatar_url" character varying(500), "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "language" "public"."users_language_enum" NOT NULL DEFAULT 'uz', "is_verified" boolean NOT NULL DEFAULT false, "is_blocked" boolean NOT NULL DEFAULT false, "rating_avg" numeric(3,2) NOT NULL DEFAULT '0', "rating_count" integer NOT NULL DEFAULT '0', "sales_count" integer NOT NULL DEFAULT '0', "region_id" uuid, "district_id" uuid, "push_token" character varying(300), "last_seen_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE TYPE "public"."categories_unit_default_enum" AS ENUM('kg', 't', 'dona', 'quti', 'qop', 'l', 'ga', 'xizmat')`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name_uz" character varying(120) NOT NULL, "name_ru" character varying(120) NOT NULL, "slug" character varying(80) NOT NULL, "icon" character varying(60), "unit_default" "public"."categories_unit_default_enum" NOT NULL DEFAULT 'kg', "parent_id" uuid, "sort_order" integer NOT NULL DEFAULT '0', "is_featured" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_categories_slug" ON "categories" ("slug") `);
        await queryRunner.query(`CREATE TABLE "listing_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "listing_id" uuid NOT NULL, "object_key" character varying(500) NOT NULL, "url" character varying(700) NOT NULL, "thumb_url" character varying(700), "sort_order" integer NOT NULL DEFAULT '0', "width" integer, "height" integer, "size_bytes" integer, CONSTRAINT "PK_73c5fd7f964a698b78f0920917c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_listing_photos_listing" ON "listing_photos" ("listing_id", "sort_order") `);
        await queryRunner.query(`CREATE TYPE "public"."listings_status_enum" AS ENUM('draft', 'pending', 'active', 'sold', 'expired', 'blocked')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_quantity_unit_enum" AS ENUM('kg', 't', 'dona', 'quti', 'qop', 'l', 'ga', 'xizmat')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_price_unit_enum" AS ENUM('kg', 't', 'dona', 'quti', 'qop', 'l', 'ga', 'xizmat')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_delivery_enum" AS ENUM('none', 'pickup', 'delivery', 'both')`);
        await queryRunner.query(`CREATE TABLE "listings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(160) NOT NULL, "description" text, "title_ru" character varying(160), "description_ru" text, "status" "public"."listings_status_enum" NOT NULL DEFAULT 'active', "seller_id" uuid NOT NULL, "category_id" uuid NOT NULL, "quantity" numeric(14,3) NOT NULL, "quantity_unit" "public"."listings_quantity_unit_enum" NOT NULL, "price" numeric(14,2) NOT NULL, "price_unit" "public"."listings_price_unit_enum" NOT NULL, "min_order" numeric(14,3), "wholesale_price" numeric(14,2), "region_id" uuid NOT NULL, "district_id" uuid NOT NULL, "lat" double precision, "lng" double precision, "harvest_date" date, "delivery" "public"."listings_delivery_enum" NOT NULL DEFAULT 'none', "season_months" integer array NOT NULL DEFAULT '{}', "is_promoted" boolean NOT NULL DEFAULT false, "promoted_until" TIMESTAMP WITH TIME ZONE, "view_count" integer NOT NULL DEFAULT '0', "call_count" integer NOT NULL DEFAULT '0', "favorite_count" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE, "sold_at" TIMESTAMP WITH TIME ZONE, "moderation_verdict" character varying(20), "moderation_reason" text, CONSTRAINT "PK_520ecac6c99ec90bcf5a603cdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_listings_promoted" ON "listings" ("is_promoted", "promoted_until") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_expires_at" ON "listings" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_seller" ON "listings" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_created_at" ON "listings" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_status_region_category" ON "listings" ("status", "region_id", "category_id") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "listing_id" uuid NOT NULL, "author_id" uuid NOT NULL, "seller_id" uuid NOT NULL, "rating" smallint NOT NULL, "comment" text, "is_hidden" boolean NOT NULL DEFAULT false, CONSTRAINT "chk_reviews_rating" CHECK (rating BETWEEN 1 AND 5), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_reviews_seller" ON "reviews" ("seller_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_reviews_listing_author" ON "reviews" ("listing_id", "author_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_reason_enum" AS ENUM('scam', 'wrong_category', 'wrong_price', 'already_sold', 'prohibited', 'spam', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('open', 'resolved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "listing_id" uuid NOT NULL, "reporter_id" uuid NOT NULL, "reason" "public"."reports_reason_enum" NOT NULL, "comment" text, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'open', "resolved_by_id" uuid, "resolution_note" text, CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_reports_reporter_listing" ON "reports" ("reporter_id", "listing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reports_listing" ON "reports" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reports_status_created" ON "reports" ("status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."price_index_unit_enum" AS ENUM('kg', 't', 'dona', 'quti', 'qop', 'l', 'ga', 'xizmat')`);
        await queryRunner.query(`CREATE TABLE "price_index" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "day" date NOT NULL, "category_id" uuid NOT NULL, "region_id" uuid, "unit" "public"."price_index_unit_enum" NOT NULL, "price_min" numeric(14,2) NOT NULL, "price_avg" numeric(14,2) NOT NULL, "price_max" numeric(14,2) NOT NULL, "trend_pct" numeric(6,2) NOT NULL DEFAULT '0', "sample_size" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3f9504845bd2be8d21d8d2871e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_price_index_lookup" ON "price_index" ("category_id", "region_id", "day") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_price_index_unique" ON "price_index" ("day", "category_id", "region_id", "unit") `);
        await queryRunner.query(`CREATE TABLE "favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "listing_id" uuid NOT NULL, CONSTRAINT "PK_890818d27523748dd36a4d1bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_favorites_user_created" ON "favorites" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_favorites_user_listing" ON "favorites" ("user_id", "listing_id") `);
        await queryRunner.query(`CREATE TABLE "chats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "listing_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "seller_id" uuid NOT NULL, "last_message_at" TIMESTAMP WITH TIME ZONE, "last_message_text" character varying(300), "buyer_unread_count" integer NOT NULL DEFAULT '0', "seller_unread_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_chats_seller" ON "chats" ("seller_id", "last_message_at") `);
        await queryRunner.query(`CREATE INDEX "idx_chats_buyer" ON "chats" ("buyer_id", "last_message_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_chats_listing_buyer" ON "chats" ("listing_id", "buyer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'image', 'system')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "chat_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "type" "public"."messages_type_enum" NOT NULL DEFAULT 'text', "body" text NOT NULL, "client_id" character varying(64), "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_messages_client_id" ON "messages" ("client_id") WHERE client_id IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_messages_chat_created" ON "messages" ("chat_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "districts" ADD CONSTRAINT "FK_4271e8e205bbdce31975c55ed3f" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1901e9aae03c8897b7dd460c27f" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_efc03fc2a5902ef17fb8a2bdcc2" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listing_photos" ADD CONSTRAINT "FK_43b5cd835afddfa23aa47339782" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_6d2846ee6b337ce5225c8c7286b" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_9315deed3e8f6d9171c23131418" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_13e894ac4a5b9e3d9ee12faefb4" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_51dc8fdcd18b7a14b255e6a3b8d" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_da74291938b03c356816a423712" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7efc8ac1a6389e4e9317435ad2b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_b138f300626648e9107e5521d0b" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_d1cdc1ed639c70f2ec0bc33e166" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_580adb3369c061e2f3cd20e7442" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_index" ADD CONSTRAINT "FK_f8b7f83045a18e4e4d1e7e5b404" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_index" ADD CONSTRAINT "FK_819d90ea2bce6f55f828b30b7a6" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_74e0699c35d78e39b229d64f34f" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_e9d682175b587bb8297d32e41f0" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_a956bacea253f921eab7bb3b14e" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_f754443807ae962605b6158bf03" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7540635fef1922f0b156b9ef74f" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7540635fef1922f0b156b9ef74f"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_f754443807ae962605b6158bf03"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_a956bacea253f921eab7bb3b14e"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_e9d682175b587bb8297d32e41f0"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_74e0699c35d78e39b229d64f34f"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593"`);
        await queryRunner.query(`ALTER TABLE "price_index" DROP CONSTRAINT "FK_819d90ea2bce6f55f828b30b7a6"`);
        await queryRunner.query(`ALTER TABLE "price_index" DROP CONSTRAINT "FK_f8b7f83045a18e4e4d1e7e5b404"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_580adb3369c061e2f3cd20e7442"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_d1cdc1ed639c70f2ec0bc33e166"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_b138f300626648e9107e5521d0b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7efc8ac1a6389e4e9317435ad2b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_da74291938b03c356816a423712"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_51dc8fdcd18b7a14b255e6a3b8d"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_13e894ac4a5b9e3d9ee12faefb4"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_9315deed3e8f6d9171c23131418"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_6d2846ee6b337ce5225c8c7286b"`);
        await queryRunner.query(`ALTER TABLE "listing_photos" DROP CONSTRAINT "FK_43b5cd835afddfa23aa47339782"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_efc03fc2a5902ef17fb8a2bdcc2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1901e9aae03c8897b7dd460c27f"`);
        await queryRunner.query(`ALTER TABLE "districts" DROP CONSTRAINT "FK_4271e8e205bbdce31975c55ed3f"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_chat_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_client_id"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chats_listing_buyer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chats_buyer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chats_seller"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP INDEX "public"."idx_favorites_user_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_favorites_user_created"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_index_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_index_lookup"`);
        await queryRunner.query(`DROP TABLE "price_index"`);
        await queryRunner.query(`DROP TYPE "public"."price_index_unit_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reports_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reports_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reports_reporter_listing"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_listing_author"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_seller"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_status_region_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_seller"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_promoted"`);
        await queryRunner.query(`DROP TABLE "listings"`);
        await queryRunner.query(`DROP TYPE "public"."listings_delivery_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_price_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_quantity_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listing_photos_listing"`);
        await queryRunner.query(`DROP TABLE "listing_photos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_slug"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_unit_default_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_districts_region"`);
        await queryRunner.query(`DROP INDEX "public"."idx_districts_region_slug"`);
        await queryRunner.query(`DROP TABLE "districts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_regions_slug"`);
        await queryRunner.query(`DROP TABLE "regions"`);
    }

}
