/**
 * All user-facing copy, in Uzbek. Kept in one file so the UZ/RU switch has a
 * single seam to work against later.
 */
export const t = {
  brand: 'Agromagnat',
  tagline: 'Yerdan dasturxongacha — vositachisiz',

  nav: {
    home: 'Bosh sahifa',
    search: 'Qidiruv',
    add: "E'lon joylash",
    favorites: 'Sevimlilar',
    profile: 'Profil',
    login: 'Kirish',
    logout: 'Chiqish',
    myListings: "Mening e'lonlarim",
  },

  home: {
    heroTitle: "Hosilingizni to'g'ridan-to'g'ri soting",
    heroSubtitle:
      "Vositachisiz. Butun O'zbekiston bo'ylab xaridorlar sizga o'zi qo'ng'iroq qiladi.",
    searchPlaceholder: 'Nima qidiryapsiz? Masalan: pomidor',
    categories: 'Kategoriyalar',
    allCategories: 'Barchasi',
    latest: "Yangi e'lonlar",
    seeAll: "Barchasini ko'rish",
  },

  search: {
    title: 'Qidiruv',
    placeholder: "Mahsulot nomi bo'yicha qidiring",
    filters: 'Filtrlar',
    apply: "Qo'llash",
    reset: 'Tozalash',
    allRegions: 'Barcha hududlar',
    allCategories: 'Barcha kategoriyalar',
    allDistricts: 'Barcha tumanlar',
    wholesale: "Ulgurji (1 t dan)",
    verified: 'Tasdiqlangan sotuvchi',
    withDelivery: 'Yetkazib berish bilan',
    priceFrom: 'Narx, dan',
    priceTo: 'Narx, gacha',
    sort: 'Saralash',
    sortNewest: 'Avval yangilari',
    sortCheapest: 'Avval arzoni',
    sortExpensive: 'Avval qimmati',
    resultsEmpty: "Hech narsa topilmadi",
    resultsEmptyHint:
      "Filtrlarni kamaytiring yoki boshqa so'z bilan qidirib ko'ring. Hududni kengaytirsangiz ham natija ko'payadi.",
    loadMore: "Yana ko'rsatish",
    found: 'topildi',
  },

  listing: {
    volume: 'Mavjud hajm',
    minOrder: 'Minimal partiya',
    harvestDate: 'Uzilgan sana',
    delivery: 'Yetkazib berish',
    wholesalePrice: 'Ulgurji narx',
    season: 'Hosil mavsumi',
    description: 'Tavsif',
    seller: 'Sotuvchi',
    call: "Qo'ng'iroq qilish",
    save: 'Saqlash',
    saved: 'Saqlangan',
    share: 'Ulashish',
    views: "ko'rish",
    verified: 'Tasdiqlangan',
    sales: 'sotuv',
    otherListings: "Sotuvchining boshqa e'lonlari",
    notFound: "E'lon topilmadi",
    notFoundHint: "E'lon o'chirilgan yoki muddati tugagan bo'lishi mumkin.",
    expired: "Muddati tugagan",
    sold: 'Sotilgan',
    topBadge: 'TOP',
    noPhoto: 'Rasm yo‘q',
  },

  auth: {
    title: 'Kirish',
    subtitle: "Telefon raqamingizni kiriting — SMS orqali kod yuboramiz",
    phoneLabel: 'Telefon raqam',
    continue: 'Davom etish',
    codeTitle: 'Kodni kiriting',
    codeSubtitle: 'raqamiga yuborilgan 6 xonali kodni kiriting',
    resend: 'Kodni qayta yuborish',
    resendIn: 'Qayta yuborish',
    nameTitle: 'Ismingiz',
    nameSubtitle: "Xaridorlar sizni shu nom bilan ko'radi",
    nameLabel: 'Ism',
    finish: 'Tayyor',
    changeNumber: "Raqamni o'zgartirish",
    devHint: 'Test rejimi: kod 000000',
  },

  addListing: {
    title: "E'lon joylash",
    stepCategory: 'Kategoriya',
    stepPhotos: 'Rasmlar',
    stepDetails: "Ma'lumotlar",
    stepReview: "Ko'rib chiqish",
    next: 'Keyingi',
    back: 'Orqaga',
    publish: "E'lonni joylash",
    titleLabel: "E'lon sarlavhasi",
    titlePlaceholder: 'Masalan: Urgut pomidori, birinchi navli',
    descriptionLabel: 'Tavsif',
    descriptionPlaceholder: "Mahsulot haqida qisqacha yozing",
    quantityLabel: 'Hajm',
    priceLabel: 'Narx',
    minOrderLabel: 'Minimal partiya',
    wholesalePriceLabel: 'Ulgurji narx',
    regionLabel: 'Viloyat',
    districtLabel: 'Tuman',
    deliveryLabel: 'Yetkazib berish',
    harvestDateLabel: 'Uzilgan sana',
    photosHint: "Ko'pi bilan 5 ta rasm. Birinchisi asosiy bo'ladi.",
    addPhoto: 'Rasm qo‘shish',
    optional: 'ixtiyoriy',
    required: 'majburiy',
    published: "E'lon joylandi",
    draftSaved: 'Qoralama saqlandi',
  },

  profile: {
    title: 'Profil',
    myListings: "Mening e'lonlarim",
    favorites: 'Sevimlilar',
    stats: 'Statistika',
    activeListings: "Faol e'lon",
    totalViews: "Ko'rishlar",
    totalCalls: "Qo'ng'iroqlar",
    settings: 'Sozlamalar',
    help: 'Yordam',
    noListings: "Sizda hali e'lon yo'q",
    noListingsHint: "Birinchi e'loningizni joylang — 2 daqiqa vaqt oladi.",
    noFavorites: "Sevimlilar bo'sh",
    noFavoritesHint: "Yoqqan e'lonni saqlang — bu yerda to'planadi.",
    edit: 'Tahrirlash',
    delete: "O'chirish",
    markSold: 'Sotildi',
    renew: 'Qayta joylash',
    confirmDelete: "E'lonni o'chirmoqchimisiz?",
  },

  chat: {
    title: 'Xabarlar',
    empty: "Yozishmalar yo'q",
    emptyHint:
      "E'lonni ochib «Yozish» tugmasini bosing — savolingizni sotuvchiga shu yerda yozasiz.",
    write: 'Yozish',
    placeholder: 'Xabar yozing...',
    send: 'Yuborish',
    sending: 'Yuborilmoqda...',
    loadEarlier: 'Oldingi xabarlar',
    notDelivered: 'Yuborilmadi',
    retry: 'Qayta yuborish',
    backToInbox: 'Barcha yozishmalar',
    youAreBuyer: 'Xaridor sifatida',
    youAreSeller: 'Sotuvchi sifatida',
    aboutListing: "E'lon",
    unreadBadge: "o'qilmagan",
  },

  reviews: {
    title: 'Baholar',
    empty: "Hali baho yo'q",
    emptyHint: 'Birinchi bo‘lib baho qoldiring — savdo yakunlangach.',
    leave: 'Baho qoldirish',
    yours: 'Sizning bahoyingiz',
    ratingLabel: 'Baho',
    commentLabel: 'Izoh',
    commentPlaceholder: 'Mahsulot sifati, yetkazib berish — qisqacha yozing',
    submit: 'Yuborish',
    thanks: 'Rahmat! Bahoyingiz qabul qilindi.',
    onlySold: "Baho faqat sotilgan e'lon uchun qo'yiladi",
    count: 'baho',
    hidden: 'Yashirilgan',
  },

  common: {
    loading: 'Yuklanmoqda...',
    error: 'Xatolik yuz berdi',
    retry: 'Qayta urinish',
    cancel: 'Bekor qilish',
    close: 'Yopish',
    save: 'Saqlash',
    from: 'dan',
    to: 'gacha',
    somPerUnit: "so'm",
  },

  footer: {
    about: 'Agromagnat haqida',
    contact: "Bog'lanish",
    terms: 'Foydalanish shartlari',
    privacy: 'Maxfiylik siyosati',
    rights: 'Barcha huquqlar himoyalangan',
  },
} as const;
